### ISSUE TITLE
The addon is not working at all in my Apex classes

### ISSUE THREAD

**Issue by fricco** [ChuckJonas/vscode-apex-autocomplete#7] opened 2017-02-10 16:44 UTC
Hello, I have done everything that was documented to configure this plug in, but this is still not working for me.
The Go To Definition option doesn't do anything.
The auto completion doesn't work for SObjects
The auto completion doesn't work for apex classes, nor method within the same class
Thanks

**Comment by ChuckJonas** [comment] 2017-02-10 17:40
@fricco  can you provide me with some additional information:

1: What OS are you running?

2: Have you properly configured `apexAutoComplete.userName` , `apexAutoComplete.password` (password+security token)  & `apexAutoComplete.instanceUrl` in your workspace settings? 

3: Is the `src` folder in the root of your workspace?

4: Open a terminal and run: `java -version`.  Output?

Also, completion for SObjects and Go-To def can take some time when first fired (should be snappy for subsequent requests though)

**Comment by fricco** [comment] 2017-02-10 17:56
@ChuckJonas I have to say, great addons do (i'm using the Apex PMD as well and I love it :) ), don't get me wrong ;)
Sorry I missed to put this portant information:
1- Windows 7 64
2- Yes, Have username and password (no token required) and using the test.salesforce.com as it's a sandbox. 
3- Maybe this is what I'm doing wrong, as I don't know where I define this, but I opened the src folder from VSCode, so the Explorer is showing that as the root. Is that what needs to be done, or there is some additional configuration to set it?
4- java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode)

I also thought that can take time, but I have been hitting the same Go-To every 30 minutes for the last 2 hours with no result ;)

**Comment by ChuckJonas** [comment] 2017-02-10 18:19
@fricco ya I think the issue might be 3.  I should maybe it configurable in the future, but right now your workspace needs to look like this in regards to `src`:

![workerqueue_cls_-_sandbox](https://cloud.githubusercontent.com/assets/5217568/22838520/d0e3f8de-ef82-11e6-8a9c-cffd4a058404.png)

**Comment by fricco** [comment] 2017-02-10 19:12
@ChuckJonas that is what I have. Although I have several other metadata folders as well, can that be an issue?
![image](https://cloud.githubusercontent.com/assets/8302696/22840291/88c424a6-ef92-11e6-9c8d-96ba89178742.png)

**Comment by ChuckJonas** [comment] 2017-02-11 01:48
@fricco no, it doesn't matter what you have under `src` as long as you have classes.  The issue is that it is expecting there to be a folder `src` under the workspace (not that the workspace _is_ `src`).  I'll see if I can add a setting so you can define where the `classes` folder is (`/` in you case).

**Comment by fricco** [comment] 2017-02-11 17:07
Ok, i tried that one as well and it doesn't work:
![image](https://cloud.githubusercontent.com/assets/8302696/22855723/3e461322-f04a-11e6-8deb-7e96b24b7d06.png)

**Comment by ChuckJonas** [comment] 2017-02-13 20:41
in that case I'm not sure...

Your best bet would be to try and call the force-tooling jar directly in your command line.

In vscode run "Open Extension Folder".  The navigate to `chuckjonas.apex-autocomplete-0.2.4/bin`.  Then try to run:

`java -jar tooling-force.jar --action= listCompletions  --projectPath='\path\to\project' --responseFilePath='path\to\outputfile.txt' --currentFilePath='path\to\currentFile.cls' --currentFileContentPath='path\to\currentFile.cls'  --line='line#' --column='column#'  --sf.username='username' --sf.password='password+st' --sf.serverurl='https://test.salesforce.com'

**Comment by eliver** [comment] 2017-02-17 02:24
@fricco Can you please take a look at java.exe process when you open vs code and then press any codes in apex files? In my case, the java process will take a huge memory usage when first activating the extension, after that the extension can be runs as expected.

**Comment by fricco** [comment] 2017-02-17 14:55
@eliver I have VSCode opened for a whole day and still this doesn't work...

**Comment by fuure** [comment] 2017-03-18 14:25
Hi, i have the same problem as @fricco , this is my tooling-force.jar output and java version

![image](https://cloud.githubusercontent.com/assets/21955834/24072930/713727dc-0bcd-11e7-8bb3-f7b365047c76.png)

Hopefully this helps

Windows 10 x64 btw

**Comment by ChuckJonas** [comment] 2017-03-19 18:50
@fricco @fricco I added a output console so we can see the commands that are running.  

If you update, you should be able to open it up by running: `Show Apex Autocomplete Debug Output`.

I could have probably added more detailed logging, but hopefully something will stick out as incorrect.

**WARNING**:  Be careful where you paste the output of this as it will include the username and password in the commands!

**Comment by fuure** [comment] 2017-03-19 19:05
I think this is why it fails

`[ERROR] CheckSyntax - Syntax error:: line: 15, pos: 1, msg: no viable alternative at input 'a.}'`
`[ERROR] CheckSyntax - Syntax error:: line: 15, pos: 1, msg: no viable alternative at input 'a.N}'`

In all my tests it seems to add a closing curly bracket at the end of the evaluated text.

**Comment by ChuckJonas** [comment] 2017-03-19 19:49
@fuure I don't think that would be the issue.  That's the excepted output of check syntax if you were to put something like this:

```
public void foo(){
  a.
}
```

Curious, do you get a green squiggle line after the statement?

![_extension_development_host__-_googleclient_cls_-_ccc-sfdc](https://cloud.githubusercontent.com/assets/5217568/24084095/7137de16-0ca9-11e7-8376-2659ab988b4b.png)

For debugging the `Go-To Definition` functionality I we want to see if the request/response of the `findSymbol` command is properly formatted.

```
Sending CMD: --action=findSymbol  --projectPath='/Users/user/Documents/mm/ccc-sfdc' --responseFilePath='/Users/user/Documents/code/apex-autocomplete/bin/findSymbolResult.json' --pollWaitMillis=1000 --maxPollRequests=1000 --currentFilePath='/Users/user/Documents/mm/ccc-sfdc/src/classes/GoogleClient.cls' --currentFileContentPath='/Users/user/Documents/code/apex-autocomplete/bin/findSymbolTmp.cls' --line='14' --column='10'  --sf.username='username' --sf.password='password' --sf.serverurl='https://test.salesforce.com'

[INFO] Executor - # Time taken: 0.021s
```

Assuming this command executes successfully, then you should be able to check `responseFilePath` to see if you got any results.

Which should look something like this:

```
RESULT=SUCCESS
[{"filePath":"/Users/user/Documents/code/apex-autocomplete/bin/findSymbolTmp.cls","line":12,"column":20,"identity":"req"}]
```

**Comment by fuure** [comment] 2017-03-19 22:01
Ok, here

![image](https://cloud.githubusercontent.com/assets/21955834/24085186/004a60ac-0cd6-11e7-9ce5-e3b6471c9c7b.png)

My "Blueprint.cls" contains just the following:

```
public with sharing class Blueprint {
	public Blueprint() {
		
	}

	public void bpInit() {
		Account a = new Account();
		a.
	} 
}
```

And about the squiggle... I get a red one, and only after saving the file.

![image](https://cloud.githubusercontent.com/assets/21955834/24085206/638053a2-0cd6-11e7-8e76-c3b4ad43b3b8.png)

Hopefully this helps, I'll be here for the rest of the day, so if I can get you anything else just ask me.

**Comment by ChuckJonas** [comment] 2017-03-20 00:34
@fuure  Does auto-complete only not work on sObjects?  That likely means the plugin is failing to authenticate.   I see that your URL is `login.salesforce.com`.  Is this a sandbox environment or a developer org?

**Comment by fuure** [comment] 2017-03-20 00:48
Yeah, it is a dev org, but I also have this very same problem with all the sandboxes on my workplace PC (Win7 x64).

Just made a new custom object to test, same problem.

Now that you mention authentication, I'm working on a personal project that involves the Tooling API which you also seem to be using in this, ¿Is it necessary to add my IP or something to the remote site settings in the security tab under Setup?

**Comment by ChuckJonas** [comment] 2017-03-20 02:48
The one thing that sticks out is how long its taking to run the commands.  The SObjects typically take a little bit longer as it has to query definitions from the tooling api, but mine typically takes about 3 seconds for the first run and < .1 seconds for all subsequent runs.

You shouldn't have to do anything configuration in salesforce for this library to work. 

Your command is almost taking a full minute to finish.  It's possible it is returning results, but the vscode auto-completion request has timed out.  Can you check the results in `responseFilePath` to see if there is anything there after the command completes?

@neowit any ideas what might be going on?

**Comment by fuure** [comment] 2017-03-20 02:59
@ChuckJonas wow, the three json files (checkSyntaxResult, findSymbolResult, listCompletionsResult) in there actually are full of the correct results.

So yeah, the length of the execution of the jar seems to be the problem here.

This is a brand new dev org with just a class I made for tests and other classes from [another project](https://github.com/afawcett/apex-toolingapi), there's a [single file](https://github.com/afawcett/apex-toolingapi/blob/master/src/classes/ToolingAPIWSDLMetadata.cls) that takes most of the execution time though.

Maybe there's something in that file that makes the scanner take its time, I'm going to delete those files from my org and see what happens. Be right back.

**Comment by neowit** [comment] 2017-03-20 08:12
Hello @fuure 

What version of tooling-force.com jar you have?

Are you saying that the the file you [linked](https://github.com/afawcett/apex-toolingapi/blob/master/src/classes/ToolingAPIWSDLMetadata.cls) seems to cause slow response time and if you remove it then response time drops ?

I just tested apex completion after adding [ToolingAPIWSDLMetadata.cls](https://github.com/afawcett/apex-toolingapi/blob/master/src/classes/ToolingAPIWSDLMetadata.cls) in my test project and could not notice any difference in response time (before and after adding ToolingAPIWSDLMetadata.cls).
I am not on MS Windows though, so not sure if that makes a difference (it should not).

Hello @ChuckJonas 
if @fuure confirms about the offending file, can you check if this file makes a noticeable difference in response time for you as well ?

**Comment by fuure** [comment] 2017-03-20 11:12
@neowit I dunno if this is correct, but this is the version pointed out inside the META-INF/manifest.mf file:

```
Manifest-Version: 1.0
Implementation-Title: tooling-force.com
Implementation-Version: 0.1-SNAPSHOT
Specification-Vendor: default
Specification-Title: tooling-force.com
Implementation-Vendor-Id: default
Specification-Version: 0.1-SNAPSHOT
Main-Class: com.neowit.apex.Runner
Implementation-Vendor: default
```

And yes, by manually calling the jar I noticed that file was taking a lot of time.

But maybe it was the [previous file in the list](https://github.com/afawcett/apex-toolingapi/blob/master/src/classes/ToolingAPIWSDL.cls). Actually is makes more sense the problem resides in the file I'm linking now since the console outputs appear before file scanning.

**Comment by neowit** [comment] 2017-03-20 12:55
@fuure 

Unfortunately Manifest file is just a dummy and does not contain actual version.
If you are able to call tooling-force.com jar manually then you can find its version like so
```
$ java -jar tooling-force.com.jar --action=version --responseFilePath='/Users/name/response_version.txt'
```

> manually calling the jar I noticed that file was taking a lot of time

How exactly did you call the jar manually ? 
Was it via java command line, like I did above for '--version' ? If so then keep in mind that this runs it in non server mode which means it needs to scan classes (and go to fetch stuff from SFDC) **every time** you invoke it.

If would be good if we could isolate the issue - is it network related or local.
When you call completion, try to call it not on SObject (this requires call to SFDC) but on something like:
```
String s;
s.<call completion here>;
```
When you do it this way it scans local classes, but does not call SFDC.
Try to call completion **twice**. First time it will scan all available sources (so it may take few seconds), but second time it should work from cached source (except for current file, which is being re-scanned every time).
Second call to completion should take less than 1 second. If it takes more then we need to see if there is something special about your apex code or config.

**Comment by ChuckJonas** [comment] 2017-03-20 16:57
@neowit the most recent version is packaged with my extension.  The extension spins up a server on start and makes all calls through it.  

Example request:  `--action=findSymbol  --projectPath='/Users/user/Documents/mm/ccc-sfdc' --responseFilePath='/Users/user/Documents/code/apex-autocomplete/bin/findSymbolResult.json' --pollWaitMillis=1000 --maxPollRequests=1000 --currentFilePath='/Users/user/Documents/mm/ccc-sfdc/src/classes/GoogleClient.cls' --currentFileContentPath='/Users/user/Documents/code/apex-autocomplete/bin/findSymbolTmp.cls' --line='14' --column='10'  --sf.username='username' --sf.password='password' --sf.serverurl='https://test.salesforce.com'`

I also saw no difference when creating the `ToolingAPIWSDLMetadata` class.  I was able to get completion on the class itself in 0.032s.

@fuure if you look at the output logs my extension is sending, do you get quicker responses?  (try running the `account.` completion multiple times)

The issue could be that an exception is getting through when I'm handling the results... However, it would be odd that some completions work and not others.  I'll try to add additional logging statements today.

**Comment by fuure** [comment] 2017-03-21 00:55
@neowit 

This is my version of the tooling-force.jar: 

```
RESULT=SUCCESS
MESSAGE: {"id":1,"text":"tooling-force.com - version: 0.3.8.0; SFDC API Version: 38.0","type":"INFO"}
MESSAGE DETAIL: {"messageId":1,"type":"DEBUG","text":"Used Memory: 2 MB"}
MESSAGE DETAIL: {"messageId":1,"type":"DEBUG","text":"Free Memory: 12 MB"}
MESSAGE DETAIL: {"messageId":1,"type":"DEBUG","text":"Total Memory: 15 MB"}
MESSAGE DETAIL: {"messageId":1,"type":"DEBUG","text":"Max Memory: 247 MB"}
```

And yeah, I called the jar manually by console, check my previous responses to @ChuckJonas where there's more detail about it. I did it just for testing purposes.

Can you check creating the ToolingAPIWSDL.cls file? I think that might be the offending one.

And I tried calling with the String, no autocomplete too.

@ChuckJonas 

I tried calling it multiple times (Inside vscode that is) and the output logs appear almost immediately, I dunno how fast the responses are because there's no response time in the output logs.

Could you check the json files not getting updated issue? I mean I don't know for sure if that's an issue, but it would be nice to know if they're updating on your side.

And for clarification, I get no completions whatsoever, regardless of the object type.

No suggestions after hitting the dot, and this is what I get if I ctrl + space at that position:

![image](https://cloud.githubusercontent.com/assets/21955834/24128002/c5bcb3c6-0db7-11e7-9b6b-fb9a7841f348.png)

Thanks to both of you guys, If there's anything I can do, just ask.

**Comment by ChuckJonas** [comment] 2017-03-21 07:16
@fuure That `ECONNRESET` seems like a likely culprit.   Might have something to do with the port (I should probably allow that to be configured).  But an error doesn't show up in the `Show Apex Autocomplete Debug Output`?

 What happens if you run this on your command line:  `java -Dfile.encoding=UTF-8  -jar [PATH_TO_JAR] --action=serverStart --port=65000 --timeoutSec=1800`

**Comment by fuure** [comment] 2017-03-21 10:42
@ChuckJonas 

Ok, some discoveries here

First, no, there are no errors showing in the Autocomplete debug output, just the calls

By starting the server manually I get an exception

`[ERROR] Executor - java.net.BindException: Address already in use: JVM_Bind`

With netstat -anb I was able to find the application using the port, `ss_conn_service.exe` is the name of the executable, and it is related to a [Samsung USB driver for phones](http://www.file.net/process/ss_conn_service.exe.html).

If I start the server in an unused port, I get no exceptions and everything seems to be starting correctly, as I only get an `Awaiting connection...` message

**Comment by ChuckJonas** [comment] 2017-03-21 16:30
@fuure that must be the issue! 

Just pushed a new update that allows you to configure the port and gives better output if it is already in use.  

can you update and set `apexAutoComplete.port` to an open port in your user setting? 

Hopefully it will work after doing that.

**Comment by fuure** [comment] 2017-03-21 16:52
@ChuckJonas works perfectly! that was it, thank you man, you just saved me from the claws of eclipse!

**Comment by ChuckJonas** [comment] 2017-03-21 16:56
awesome! thanks for helping to make this tool better.  Let me know if you have any other feedback

**Closed by ChuckJonas** 2017-03-21 16:56 UTC
